/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;

import Code.UserAuth;
import static Code.UserAuth.name;
import static Code.UserAuth.saveCookie;
import static Code.UserAuth.sessionToken;
import javax.swing.JOptionPane;

/**
 *
 * @author manul
 */
public class CookiesDialog extends javax.swing.JDialog {

    static boolean disabledstatus;
    
    private boolean logoutButtonClicked = true;
    
    public static boolean disabledStatus = true;

    

    /**
     * Creates new form CookiesDialog
     */
    public CookiesDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
//        if(UserAuth.autoLogin())
//        {
//            disabledStatus = true;
//        }
    }
    
//    public static void checkStatus()
//    {
//        if(UserAuth.autoLogin())
//        {
//            disabledStatus = true;
//        }
//    }
    
    // Check if there's a saved session for auto-login
//    public static void checkAutoLogin() {
//        if (UserAuth.autoLogin()) {
////            JOptionPane.showMessageDialog(this, "Auto-login successful!", "Welcome Back", JOptionPane.INFORMATION_MESSAGE);
//            Home home = new Home();
//            home.setVisible(true);
//            
////            checkcookies = false;
//            
//             Ensure LoginPage closes properly
//            javax.swing.SwingUtilities.invokeLater(() -> {
//            this.setVisible(false);
//            this.dispose();
//            });
//        }
//        else
//        {
//            LoginPage login = new LoginPage();
//            login.setVisible(true);
//        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtLevels = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        DeclineBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        AcceptBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(145, 115, 74));

        jPanel2.setBackground(new java.awt.Color(221, 157, 66));

        txtLevels.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtLevels.setForeground(new java.awt.Color(255, 255, 255));
        txtLevels.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtLevels.setText("Our gaming app uses cookies to improve your browsing experience. ");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("By using our site you agree to the use of cookies.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtLevels, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(txtLevels, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        DeclineBtn.setBackground(new java.awt.Color(221, 157, 66));
        DeclineBtn.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        DeclineBtn.setForeground(new java.awt.Color(104, 74, 10));
        DeclineBtn.setText("Decline");
        DeclineBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DeclineBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeclineBtnMouseClicked(evt);
            }
        });
        DeclineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeclineBtnActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\manul\\OneDrive\\Desktop\\Y3S1\\DSA\\Assignment\\cookie_629587.png")); // NOI18N

        AcceptBtn.setBackground(new java.awt.Color(221, 157, 66));
        AcceptBtn.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        AcceptBtn.setForeground(new java.awt.Color(104, 74, 10));
        AcceptBtn.setText("Accept ");
        AcceptBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AcceptBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AcceptBtnMouseClicked(evt);
            }
        });
        AcceptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(AcceptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(DeclineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeclineBtn)
                    .addComponent(AcceptBtn))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeclineBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeclineBtnMouseClicked
        // TODO add your handling code here:
        logoutButtonClicked = true; // Mark that Play was clicked
        JOptionPane.showMessageDialog(this, "Signup Successful! Please login.");
        disabledStatus = false;
        LoginPage login = new LoginPage(); // Create an instance of LoginPage
        login.setVisible(true); // Show Login page
        this.dispose(); // Close signup window
       
    }//GEN-LAST:event_DeclineBtnMouseClicked

    private void DeclineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeclineBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeclineBtnActionPerformed

    private void AcceptBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AcceptBtnMouseClicked
        // TODO add your handling code here:
         logoutButtonClicked = true; // Mark that Play was clicked
        JOptionPane.showMessageDialog(this, "Signup Successful! Please login.");
        sessionToken = UserAuth.generateSalt();
        saveCookie(name);
        disabledStatus = true;
//        UserAuth.sessionActive();
        LoginPage login = new LoginPage(); // Create an instance of LoginPage
        login.setVisible(true); // Show Login page
        this.dispose(); // Close signup window
    }//GEN-LAST:event_AcceptBtnMouseClicked

    private void AcceptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AcceptBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CookiesDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CookiesDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CookiesDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CookiesDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CookiesDialog dialog = new CookiesDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcceptBtn;
    private javax.swing.JButton DeclineBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel txtLevels;
    // End of variables declaration//GEN-END:variables
}
