/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;

import Code.DBManager;

import Code.UserAuth;
import static Code.UserAuth.sessionToken;
import GUI.LoginPage;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.URL;
import org.json.JSONArray;
import org.json.JSONObject;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author manul
 */
public class ProfileDialog extends javax.swing.JDialog {
    private boolean logoutButtonClicked = false; // Track if logout button was clicked
    
    public static int check = 0;
    
    private static final String FILE_PATH = "C:\\Users\\manul\\OneDrive\\Desktop\\Y3S1\\DSA\\Assignment\\GameDemo\\src\\main\\java\\Code\\players.json"; // Adjust the file path
    

    /**
     * Creates new form ProfileDialog
     */
    
    
    public ProfileDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.setDefaultCloseOperation(GameDialog.DISPOSE_ON_CLOSE); // Allow closing
        this.addWindowListener(new WindowAdapter() {
        @Override
        public void windowClosed(WindowEvent e) { 
            if (!logoutButtonClicked) { // Only return to home if logout wasn't clicked
                new Home().setVisible(true);
            }
        }
    });
        
//        int points = GameLevel.getPoints();
//        txtPoints.setText("points: "+points);
        
        
        
//        String name = LoginPage.getprofilename();
        String name = UserAuth.name;
        txtName.setText(""+name);
        
//        int completelevels = UserAuth.addcompleteLevels(name, 1);
//        txtLevels.setText("Completed Levels: " + completelevels);
//        
//        int score = UserAuth.updateScore(name, points);
//        txtPoints.setText("Points: " + score);
        
//         Fetch completed levels from the JSON file for the logged-in user
        loadCompletedLevel(name); // Fetch levels for the logged-in user

        loadScore(name);
        
        
                  
        }
    
//    // Fetch the completed levels for a given user from the JSON file
    private void loadCompletedLevel(String username) 
    {
        JSONArray users = DBManager.readJSONFile(FILE_PATH);

        for (int i = 0; i < users.length(); i++) 
        {
            JSONObject user = users.getJSONObject(i);
            if (user.getString("Name").equals(username)) 
            { // Find user
                int completedLevel = user.getInt("completedLevel");
//                System.out.println("Completed Level Retrieved: " + completedLevel);
                txtLevels.setText("Completed Levels: " + completedLevel);
            }
//            break;
        }
    }
    
    private void loadScore(String username) 
    {
        JSONArray users = DBManager.readJSONFile(FILE_PATH);

        for (int i = 0; i < users.length(); i++) 
        {
            JSONObject user = users.getJSONObject(i);
            if (user.getString("Name").equals(username)) 
            { // Find user
                int score = user.getInt("score"); // Default to 0 if missing
//                System.out.println("Score Retrieved: " + score);
                txtPoints.setText("Points: " + score); // Display score in profile
            }
//            break;
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtLevels = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtPoints = new javax.swing.JLabel();
        LogoutBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(145, 115, 74));

        jPanel2.setBackground(new java.awt.Color(221, 157, 66));

        txtLevels.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtLevels.setForeground(new java.awt.Color(255, 255, 255));
        txtLevels.setText("Completed Level: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtLevels, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(txtLevels)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(221, 157, 66));

        txtPoints.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPoints.setForeground(new java.awt.Color(255, 255, 255));
        txtPoints.setText("Points: ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(txtPoints)
                .addGap(16, 16, 16))
        );

        LogoutBtn.setBackground(new java.awt.Color(221, 157, 66));
        LogoutBtn.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        LogoutBtn.setForeground(new java.awt.Color(104, 74, 10));
        LogoutBtn.setText("Logout");
        LogoutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutBtnMouseClicked(evt);
            }
        });
        LogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBtnActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\manul\\OneDrive\\Desktop\\Y3S1\\DSA\\Assignment\\Images\\profile.png")); // NOI18N
        jLabel4.setText("jLabel4");

        txtName.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        txtName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(LogoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(34, 34, 34)))
                .addComponent(LogoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutBtnMouseClicked
        // TODO add your handling code here:
        logoutButtonClicked = true; // Mark that Play was clicked
        this.dispose(); // Close the pop-up
//        sessionToken = null;
        UserAuth.logout(); // Clear session
        CookiesDialog.disabledStatus = false;
        check = 1;
        new LoginPage().setVisible(true); // Open Level 1 game


//    try {
//        // Step 1: Trigger the LogoutServlet via HTTP request
//        URL url = new URL("http://localhost:8080/GameDemo/LogoutServlet"); 
//        HttpURLConnection connection = (HttpURLConnection) url.openConnection();
//        connection.setRequestMethod("POST");
//        connection.setDoOutput(true);

        // Step 2: Optional: Send any parameters if needed (e.g., session id, username)
//        String urlParameters = "dummyParameter=dummyValue"; // Only if necessary
//        try (OutputStream os = connection.getOutputStream()) {
//            byte[] input = urlParameters.getBytes(StandardCharsets.UTF_8);
//            os.write(input, 0, input.length);
//        }

        // Step 3: Handle response and check if logout was successful
//        int responseCode = connection.getResponseCode();
//        if (responseCode == HttpURLConnection.HTTP_OK) {
//            JOptionPane.showMessageDialog(this, "You have successfully logged out!");
//
//            // Step 4: Redirect to the LoginPage (open the JFrame for login)
//            LoginPage loginPage = new LoginPage();
//            loginPage.setVisible(true);
//            this.dispose(); // Close the current page (HomePage or wherever you are)
//        } else {
//            JOptionPane.showMessageDialog(this, "Logout failed. Please try again.");
//        }
//
//    } catch (IOException e) {
//        JOptionPane.showMessageDialog(this, "Error during logout: " + e.getMessage());
//    }

//try {
//        // Redirect to LogoutServlet when logout is triggered
//        LogoutServlet.logoutUser();
//        
//        // Show a confirmation message
//        JOptionPane.showMessageDialog(this, "You have successfully logged out!");
//        
//        // Redirect the user to the login page
//        LoginPage loginPage = new LoginPage();
//        loginPage.setVisible(true);
//        this.dispose(); // Close the current page (HomePage or wherever you are)
//    } catch (Exception e) {
//        JOptionPane.showMessageDialog(this, "Error during logout: " + e.getMessage());
//    }

    }//GEN-LAST:event_LogoutBtnMouseClicked

    private void LogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfileDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfileDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfileDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfileDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProfileDialog dialog = new ProfileDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogoutBtn;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel txtLevels;
    private javax.swing.JLabel txtName;
    private javax.swing.JLabel txtPoints;
    // End of variables declaration//GEN-END:variables
}
