/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Code.DBManager;
import Code.UserAuth;
import static Code.UserAuth.name;
import javax.swing.JOptionPane;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 *
 * @author manul
 */
public class SetPassword extends javax.swing.JFrame {
    
    private boolean checksubmit = false;
    
    private static final String CODES_FILE = "C:\\Users\\manul\\OneDrive\\Desktop\\Y3S1\\DSA\\Assignment\\GameDemo\\src\\main\\java\\Code\\resetCodes.json";

    private String code;
    
    private String email;
    /**
     * Creates new form SetPassword
     */
    public SetPassword() {
        initComponents();
    }
    
    private void insertDetails()
    {
        JSONArray resetCodes = DBManager.readJSONFile(CODES_FILE);

        for (int i = 0; i < resetCodes.length(); i++) 
        {
            JSONObject resetEntry = resetCodes.getJSONObject(i);
            code = resetEntry.getString("code");
            email = resetEntry.getString("email");
        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        paratxt = new javax.swing.JLabel();
        codetxt = new javax.swing.JTextField();
        confirmtxt = new javax.swing.JTextField();
        SubmitBtn = new javax.swing.JButton();
        txtLevels1 = new javax.swing.JLabel();
        backBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(145, 115, 74));

        jPanel2.setBackground(new java.awt.Color(221, 157, 66));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("mix of uppercases, letters, numbers, and symbols");

        paratxt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        paratxt.setForeground(new java.awt.Color(255, 255, 255));
        paratxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paratxt.setText("Password requires a minimum of 6 characters and contains .");

        codetxt.setBackground(new java.awt.Color(221, 157, 66));
        codetxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        codetxt.setText("Enter Your New Password");
        codetxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75, 45, 24)));
        codetxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                codetxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                codetxtFocusLost(evt);
            }
        });
        codetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codetxtActionPerformed(evt);
            }
        });

        confirmtxt.setBackground(new java.awt.Color(221, 157, 66));
        confirmtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        confirmtxt.setText("Enter confirm password");
        confirmtxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(75, 45, 24)));
        confirmtxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                confirmtxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                confirmtxtFocusLost(evt);
            }
        });
        confirmtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmtxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(paratxt, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confirmtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(paratxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(codetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(confirmtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        SubmitBtn.setBackground(new java.awt.Color(221, 157, 66));
        SubmitBtn.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        SubmitBtn.setForeground(new java.awt.Color(104, 74, 10));
        SubmitBtn.setText("Continue");
        SubmitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SubmitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitBtnMouseClicked(evt);
            }
        });
        SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtnActionPerformed(evt);
            }
        });

        txtLevels1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txtLevels1.setForeground(new java.awt.Color(255, 255, 255));
        txtLevels1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtLevels1.setText("Set password");

        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        backBtn.setText("< Back");
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtLevels1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(SubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLevels1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SubmitBtn)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codetxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codetxtFocusGained
        // TODO add your handling code here:
        if(codetxt.getText().equals("Enter Your New Password"))
        {
            codetxt.setText("");
        }
    }//GEN-LAST:event_codetxtFocusGained

    private void codetxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codetxtFocusLost
        // TODO add your handling code here:
        if(codetxt.getText().equals(""))
        {
            codetxt.setText("Enter Your New Password");
        }
    }//GEN-LAST:event_codetxtFocusLost

    private void codetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codetxtActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_codetxtActionPerformed

    private void SubmitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitBtnMouseClicked
        // TODO add your handling code here:

        checksubmit = true;
        if(codetxt.getText().equals(confirmtxt.getText()))
        {
            String newPassword = confirmtxt.getText();
            UserAuth.resetPassword(email, code, newPassword);
            JOptionPane.showMessageDialog(this, "Set the password Successful!");
            LoginPage login = new LoginPage(); // Create an instance of HomePage
            login.setVisible(true); // Show Login page
//            new ForgotPassword().setVisible(true);
            this.dispose(); // Close signup window
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Passwords do not match!");
            codetxt.setText("Enter Your New Password");
            confirmtxt.setText("Enter confirm password");
        }

    }//GEN-LAST:event_SubmitBtnMouseClicked

    private void SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitBtnActionPerformed

    private void backBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseClicked
        // TODO add your handling code here:
        ResetPassword reset = new ResetPassword(); // Create an instance of HomePage
        reset.setVisible(true); // Show Login page
        this.dispose(); // Close signup window
    }//GEN-LAST:event_backBtnMouseClicked

    private void confirmtxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmtxtFocusGained
        // TODO add your handling code here:
        if(confirmtxt.getText().equals("Enter confirm password"))
        {
            confirmtxt.setText("");
        }
    }//GEN-LAST:event_confirmtxtFocusGained

    private void confirmtxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmtxtFocusLost
        // TODO add your handling code here:
        if(confirmtxt.getText().equals(""))
        {
            confirmtxt.setText("Enter confirm password");
        }
    }//GEN-LAST:event_confirmtxtFocusLost

    private void confirmtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmtxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SetPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SubmitBtn;
    private javax.swing.JLabel backBtn;
    private javax.swing.JTextField codetxt;
    private javax.swing.JTextField confirmtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel paratxt;
    private javax.swing.JLabel txtLevels1;
    // End of variables declaration//GEN-END:variables
}
